<?php

/**
 * @file
 * Contains acreat_actualite.module
 */

/**
 * Implements hook_theme()
 */
function acreat_actualite_theme($existing, $type, $theme, $path) {
  return array(
    'acreat_actualite_pager' => array(
      'variables' => array(
        'previous_url'   => NULL,
        'previous_title' => NULL,
        'next_url'       => NULL,
        'next_title'     => NULL
      ),
    ),
  );
}