custom:
  -
    path: /
    priority: !!float 1
entity_types:
  node:
    yamlform:
      index: 1
      priority: 0.5
    page:
      index: 1
      priority: 0.5
    actualite:
      index: 1
      priority: 0.5
settings:
  max_links: 2000
  cron_generate: true
  remove_duplicates: true
  skip_untranslated: false
  batch_process_limit: 1500
_core:
  default_config_hash: Gzm-Hm6hFi622JTbULwDXMxPi33rj_mF0pi1ggq6sFQ
langcode: fr
