settings:
  default_page_base_path: formulaire
  default_form_closed_message: 'Ce formulaire est fermé à toute nouvelle soumission.'
  default_form_exception_message: 'Une erreur est survenue durand l''affichage du formulaire. Si le problème persiste, merci de contacter l''administrateur du site.  '
  default_form_submit_label: Soumettre
  default_form_confidential_message: 'Ce formulaire est confidentiel. Merci de vous <a href="[site:login-url]/logout?destination=[current-page:url:relative]">déconnecter</a> pour le soumettre.'
  default_form_novalidate: false
  default_form_details_toggle: true
  default_wizard_prev_button_label: '< Page précédente'
  default_wizard_next_button_label: 'Page suivante >'
  default_wizard_start_label: Début
  default_wizard_complete_label: Terminé
  default_preview_next_button_label: Aperçu
  default_preview_prev_button_label: '< Précédent'
  default_preview_message: 'Veuillez contrôler votre soumission. Votre soumission ne sera complétée qu''une fois le bouton "Envoyer" cliqué.'
  default_draft_button_label: 'Enregistrer le brouillon'
  default_draft_saved_message: 'Soumissions enregistrées. Vous pourrez revenir sur ce formulaire plus tard, cela restaurera les valeurs actuelles.'
  default_draft_loaded_message: 'Un formulaire partiellement complété a été trouvé. Veuillez compléter les portions restantes.'
  default_confirmation_message: 'Nouvelle soumission du formulaire : [yamlform:title].'
  default_limit_total_message: 'Les soumissions de ce formulaire ne vous sont plus permises.'
  default_limit_user_message: 'Les soumissions de ce formulaire ne vous sont plus permises.'
export:
  delimiter: ','
  header_format: label
  header_prefix: true
  header_prefix_label_delimiter: ': '
  header_prefix_key_delimiter: __
  options_format: compact
  options_item_format: label
  entity_reference_format: link
  composite_element_item_format: label
  likert_answers_format: label
batch:
  default_batch_export_size: 500
  default_batch_update_size: 500
  default_batch_delete_size: 500
elements:
  allowed_tags: admin
  wrapper_classes: "container-inline clearfix\r\nform--inline clearfix\r\nmessages messages--error\r\nmessages messages--warning\r\nmessages messages--status\r\n"
  classes: "container-inline clearfix\r\nform--inline clearfix\r\nmessages messages--error\r\nmessages messages--warning\r\nmessages messages--status\r\n"
  default_description_display: ''
  default_max_filesize: ''
  default_file_extensions: 'gif jpg png bmp eps tif pict psd txt rtf html odf pdf doc docx ppt pptx xls xlsx xml avi mov mp3 ogg wav bz2 dmg gz jar rar sit svg tar zip'
format:
  checkbox: ''
  checkboxes: ''
  color: ''
  date: ''
  datelist: ''
  datetime: ''
  email: ''
  entity_autocomplete: ''
  hidden: ''
  language_select: ''
  machine_name: ''
  managed_file: ''
  number: ''
  password: ''
  password_confirm: ''
  processed_text: ''
  radios: ''
  range: ''
  search: ''
  select: ''
  table: ''
  tableselect: ''
  tel: ''
  textarea: ''
  textfield: ''
  text_format: ''
  url: ''
  value: ''
  yamlform_address: ''
  yamlform_autocomplete: ''
  yamlform_checkboxes_other: ''
  yamlform_codemirror: ''
  yamlform_contact: ''
  yamlform_creditcard: ''
  yamlform_creditcard_number: ''
  yamlform_element: ''
  yamlform_email_confirm: ''
  yamlform_email_multiple: ''
  yamlform_entity_checkboxes: ''
  yamlform_entity_radios: ''
  yamlform_entity_select: ''
  yamlform_likert: ''
  yamlform_markup: ''
  yamlform_name: ''
  yamlform_radios_other: ''
  yamlform_rating: ''
  yamlform_select_other: ''
  yamlform_signature: ''
  yamlform_toggle: ''
mail:
  default_from_mail: '[site:mail]'
  default_from_name: '[site:name]'
  default_subject: 'Form submission from: [yamlform-submission:source-entity]'
  default_body_text: "Soumis le [yamlform-submission:created]\r\nSoumis par: [yamlform-submission:user]\r\n\r\nInformations de la soumission:\r\n[yamlform-submission:values]\r\n"
  default_body_html: "<p>Soumis le [yamlform-submission:created]</p>\r\n<p>Soumis par: [yamlform-submission:user]</p>\r\n<p>Submitted values are:</p>\r\n[yamlform-submission:values]\r\n"
test:
  types: "checkbox:\r\n  - true\r\ncolor:\r\n  - '#ffffcc'\r\n  - '#ffffcc'\r\n  - '#ccffff'\r\ndate:\r\n  - '1942-06-18'\r\n  - '1940-07-07'\r\n  - '1943-02-25'\r\n  - '1940-10-09'\r\ndatetime:\r\n  - '1942-06-18'\r\n  - '1940-07-07'\r\n  - '1943-02-25'\r\n  - '1940-10-09'\r\ndatelist:\r\n  - '1942-06-18'\r\n  - '1940-07-07'\r\n  - '1943-02-25'\r\n  - '1940-10-09'\r\nemail:\r\n  - 'example@example.com'\r\n  - 'test@test.com'\r\n  - 'random@random.com'\r\nlanguage_select:\r\n  - en\r\nmachine_name:\r\n  - 'loremipsum'\r\n  - 'oratione'\r\n  - 'dixisset'\r\ntel:\r\n  - '123-456-7890'\r\n  - '098-765-4321'\r\ntextarea:\r\n  - 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Negat esse eam, inquit, propter se expetendam. Primum Theophrasti, Strato, physicum se voluit; Id mihi magnum videtur. Itaque mihi non satis videmini considerare quod iter sit naturae quaeque progressio. Quare hoc videndum est, possitne nobis hoc ratio philosophorum dare. Est enim tanti philosophi tamque nobilis audacter sua decreta defendere.'\r\n  - 'Huius, Lyco, oratione locuples, rebus ipsis ielunior. Duo Reges: constructio interrete. Sed haec in pueris; Sed utrum hortandus es nobis, Luci, inquit, an etiam tua sponte propensus es? Sapiens autem semper beatus est et est aliquando in dolore; Immo videri fortasse. Paulum, cum regem Persem captum adduceret, eodem flumine invectio? Et ille ridens: Video, inquit, quid agas;'\r\n  - 'Quae cum dixisset, finem ille. Quamquam non negatis nos intellegere quid sit voluptas, sed quid ille dicat. Progredientibus autem aetatibus sensim tardeve potius quasi nosmet ipsos cognoscimus. Gloriosa ostentatio in constituendo summo bono. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Duarum enim vitarum nobis erunt instituta capienda. Comprehensum, quod cognitum non habet? Qui enim existimabit posse se miserum esse beatus non erit. Causa autem fuit huc veniendi ut quosdam hinc libros promerem. Nunc omni virtuti vitium contrario nomine opponitur.'\r\ntext_format:\r\n  - '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Negat esse eam, inquit, propter se expetendam. Primum Theophrasti, Strato, physicum se voluit; Id mihi magnum videtur. Itaque mihi non satis videmini considerare quod iter sit naturae quaeque progressio. Quare hoc videndum est, possitne nobis hoc ratio philosophorum dare. Est enim tanti philosophi tamque nobilis audacter sua decreta defendere.</p>'\r\n  - '<p>Huius, Lyco, oratione locuples, rebus ipsis ielunior. Duo Reges: constructio interrete. Sed haec in pueris; Sed utrum hortandus es nobis, Luci, inquit, an etiam tua sponte propensus es? Sapiens autem semper beatus est et est aliquando in dolore; Immo videri fortasse. Paulum, cum regem Persem captum adduceret, eodem flumine invectio? Et ille ridens: Video, inquit, quid agas;</p>'\r\n  - '<p>Quae cum dixisset, finem ille. Quamquam non negatis nos intellegere quid sit voluptas, sed quid ille dicat. Progredientibus autem aetatibus sensim tardeve potius quasi nosmet ipsos cognoscimus. Gloriosa ostentatio in constituendo summo bono. Qui-vere falsone, quaerere mittimus-dicitur oculis se privasse; Duarum enim vitarum nobis erunt instituta capienda. Comprehensum, quod cognitum non habet? Qui enim existimabit posse se miserum esse beatus non erit. Causa autem fuit huc veniendi ut quosdam hinc libros promerem. Nunc omni virtuti vitium contrario nomine opponitur.</p>'\r\nurl:\r\n  - 'http://example.com'\r\n  - 'http://test.com'\r\nyamlform_creditcard_number:\r\n  - '4111111111111111'\r\nyamlform_email_confirm:\r\n  - 'example@example.com'\r\n  - 'test@test.com'\r\n  - 'random@random.com'\r\nyamlform_email_multiple:\r\n  - 'example@example.com, test@test.com, random@random.com'\r\n"
  names: "first_name:\r\n  - 'John'\r\n  - 'Paul'\r\n  - 'Ringo'\r\n  - 'George'\r\nlast_name:\r\n  - 'Lennon'\r\n  - 'McCartney'\r\n  - 'Starr'\r\n  - 'Harrison'\r\naddress:\r\n  - '10 Main Street'\r\n  - '11 Brook Alley Road. APT 1'\r\nzip:\r\n  - '11111'\r\n  - '12345'\r\n  - '12345-6789'\r\nphone:\r\n  - '123-456-7890'\r\n  - '098-765-4321'\r\ncity:\r\n  - 'Springfield'\r\n  - 'Pleasantville'\r\n  - 'Hill Valley'\r\nurl:\r\n  - 'http://example.com'\r\n  - 'http://test.com'\r\ndefault:\r\n  - 'Loremipsum'\r\n  - 'Oratione'\r\n  - 'Dixisset'\r\n"
ui:
  video_display: dialog
  details_save: true
  dialog_disabled: false
  html_editor_disabled: false
langcode: fr
third_party_settings: {  }
_core:
  default_config_hash: 5gAbFU_IFamaiI-AoTy7HUs1Z9iAjf1qX8oyFDusH1g
